name: SAST y SCA Romper con dos yml
 
on:
  push:
  pull_request:
  workflow_dispatch:
 
jobs:
  sast-scan:
    name: Fluid Attacks SAST
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Fluid Attacks SAST
        id: sast_scan
        run: |
          docker run --rm \
            -v "$PWD:/src" \
            fluidattacks/sast:latest \
            sast --strict scan /src/config.yaml

          mv Fluid-Attacks-Results.csv Fluid-Attacks-Results-sast.csv

      - name: Upload SAST CSV
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: sast-results
          path: Fluid-Attacks-Results-sast.csv

  sca-scan:
    name: Fluid Attacks SCA
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Fluid Attacks SCA
        id: sca_scan
        run: |
          docker run --rm \
            -v "$PWD:/src" \
            fluidattacks/sca:latest \
            sca --strict scan /src/config.yaml

          mv Fluid-Attacks-Results.csv Fluid-Attacks-Results-sca.csv

      - name: Upload SCA CSV
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: sca-results
          path: Fluid-Attacks-Results-sca.csv

  trivy-scan:
    name: Trivy Security Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Trivy
        run: |
          sudo apt-get update -y
          sudo apt-get install -y wget
          wget https://github.com/aquasecurity/trivy/releases/latest/download/trivy_0.67.2_Linux-64bit.deb
          sudo dpkg -i trivy_0.67.2_Linux-64bit.deb

      - name: Run Trivy Filesystem Scan
        run: trivy fs --security-checks vuln,misconfig,secret --format json -o trivy-results.json .
        continue-on-error: true

      - name: Upload Trivy Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: trivy-security-report
          path: trivy-results.json